### ISSUE TITLE
احذف هاذ الصطر كله 

### ISSUE THREAD

**Issue by MOA-YAD** [thejmthon/sbb_b0#11]
https://github.com/thejmthon/sbb_b0/blob/cd254f851fb03d4c8903a2105e6144562f3c0bbb/sbb_b/plugins/%D8%A7%D9%84%D8%A7%D9%88%D8%A7%D9%85%D8%B1.py#L177

**Comment by jmthonr** [comment]
fix that

**Comment by MOA-YAD** [comment]
> fix that

Welcome
