### ISSUE TITLE
زياده بصيطه (/)بعد كلمه (        "**⌔∮ قائـمة اوامر التسلية**: ) مخربه شويه من شكل القائمه

### ISSUE THREAD

**Issue by MOA-YAD** [thejmthon/sbb_b0#6]
https://github.com/thejmthon/sbb_b0/blob/8aac09b17b5fdbfb7acfe8ad55459281930231d5/sbb_b/plugins/%D8%A7%D9%84%D8%A7%D9%88%D8%A7%D9%85%D8%B1.py#L173

**Comment by jmthonr** [comment]
solved
